### PR TITLE
Problem: recv_fair_queue repeat the nex list_wrap_around function

### PR DESCRIPTION
**Pull request by AxelVoitier**
Refactoring

### CODE REVIEW

**Comment by hintjens** [comment]
FWIW if you push multiple commits one after the other without waiting for a merge, it combines into a single pull request, which is neat (one merge does them all).

**Comment by AxelVoitier** [comment]
I was trying to avoid this, playing with branches, so the pull request contains only its related changes (I did meant to separate #9 and #8, if that what you meant ;)).

**Comment by hintjens** [comment]
Yes, I noticed you were waiting with pushes. No need... you can batch
commits up, it works nicely.

**Comment by AxelVoitier** [comment]
OK :)

**Pull request merged**
